### ISSUE TITLE
Addition Of Code Of Conduct

### ISSUE THREAD

**Issue by Mannuel25** [ufosc/GatorWiki#17]
I suggest we have a [Code Of Conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project). We can make use of [Contributor Covenant](https://www.contributor-covenant.org/) is a code of conduct that you may customize to convey both these core beliefs and the unique norms and values that define your community.

If I'm granted the go-ahead, I can add it to the repository.

**Comment by awhigham9** [comment]
Agreed. I am good with with using the Contributor Covenant. Adding the markdown version to the repository sounds good. Substitute "[INSERT CONTACT METHOD]" with "gator.osc@gmail.com" and it should be good.

Thanks for raising this issue!

**Comment by Mannuel25** [comment]
> Agreed. I am good with with using the Contributor Covenant. Adding the markdown version to the repository sounds good. Substitute "[INSERT CONTACT METHOD]" with "[gator.osc@gmail.com](mailto:gator.osc@gmail.com)" and it should be good.
> 
> Thanks for raising this issue!

Okay, that will I do.

Thanks for assigning this to me🙏

**Comment by awhigham9** [comment]
Resolved by #18
